CREATE TABLE "questionnaire_submissions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"client_name" text,
	"price_amount" numeric(12, 2),
	"currency" text,
	"payment_terms" text,
	"payment_method" text,
	"business_name" text NOT NULL,
	"contact_name" text NOT NULL,
	"contact_email" text NOT NULL,
	"contact_phone" text,
	"physical_address" text,
	"business_type" text,
	"offering" text,
	"catalogue_size" text,
	"business_aim" text,
	"has_existing_website" boolean,
	"existing_website_url" text,
	"site_goals" text,
	"notes" text,
	"start_date" text,
	"finish_date" text,
	"logo_base64" text,
	"logo_content_type" text,
	"sla_pdf" text,
	"brief_pdf" text,
	"signed_name" text,
	"signed_id_number" text,
	"signed_at" timestamp with time zone,
	"signed_ip" text,
	"email_sent" boolean DEFAULT false NOT NULL,
	"status" text DEFAULT 'submitted' NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
