import DecisionTreeCanvas, { type CanvasDecision, type CanvasStage } from "./DecisionTreeCanvas";

const decision = (
  id: CanvasDecision["id"], owner: string, question: string, why: string,
  yes: string, yesNext: string, no: string, noNext: string, record: string,
): CanvasDecision => ({ id, owner, question, why, yes, yesNext, no, noNext, record });

const stages: CanvasStage[] = [
  {
    number: "01",
    title: "Qualify the booked review",
    purpose: "Protect the fixed half-day by confirming that one observable process can answer one useful decision.",
    decisions: [
      decision("D01", "Commercial owner", "Has the review been formally booked and commercially released?", "A tentative date or verbal intention is not authority to reserve fieldwork.", "Open the controlled review record.", "D02 · BOUNDARY TEST", "State the outstanding acceptance or payment condition.", "HOLD · COMMERCIAL RELEASE", "Booking reference, accepted terms, invoice or payment condition and release date."),
      decision("D02", "Process lead", "Is the requested scope one operational process at one site?", "The fixed product is deliberately bounded; multiple processes or sites require a different evidence plan.", "Test whether the review has a clear decision to support.", "D03 · DECISION PURPOSE", "See whether the request can be narrowed without losing its purpose.", "D04 · NARROWING TEST", "Proposed process, site, adjacent processes and explicit exclusions."),
      decision("D03", "Process lead + client owner", "Can the client state the decision this review must support?", "A review without a decision becomes open-ended observation and generic advice.", "Record the decision question in plain language.", "D05 · PROCESS OWNER", "Use a short clarification to frame the decision before fieldwork.", "D04 · NARROWING TEST", "Decision, decision maker, timing and consequence of doing nothing."),
      decision("D04", "Process lead", "Can the scope and decision be narrowed in one short scoping conversation?", "The scoping call protects the paid half-day; it should not become free discovery.", "Confirm the revised boundary and repeat the qualification tests.", "RETURN · D02", "Recommend the appropriate audit, project scoping or clean close.", "END · WRONG DIAGNOSTIC", "Clarification asked, revised boundary, reason and recommended alternative."),
      decision("D05", "Client sponsor", "Is there one accountable owner for the process result?", "Somebody must be able to explain the intended result and make the final factual corrections.", "Confirm the owner’s participation and authority.", "D06 · PROCESS PERFORMER", "Appoint an accountable owner before the date is protected.", "HOLD · PROCESS OWNER", "Owner, result, authority, contact route and attendance commitment."),
      decision("D06", "Client owner", "Will somebody who actually performs the process participate?", "A process cannot be understood solely through management descriptions or procedure documents.", "Confirm the performer and the work they will demonstrate.", "D07 · SITE AND DATE", "Find an available performer or move the review date.", "HOLD · PERFORMER", "Performer, role, shift, location and process steps they execute."),
      decision("D07", "Operations coordinator", "Are the on-site date, access window and first meeting point confirmed?", "A half-day loses its value quickly when access and logistics consume the observation window.", "Issue the preparation request and diary confirmation.", "D08 · PRE-REVIEW BRIEF", "Resolve the site access or schedule condition first.", "HOLD · FIELDWORK ACCESS", "Date, hours, site, arrival point, access owner and known restrictions."),
    ],
  },
  {
    number: "02",
    title: "Prepare without pre-solving",
    purpose: "Gather enough context to observe intelligently without turning the preparation into analysis by questionnaire.",
    decisions: [
      decision("D08", "Operations coordinator", "Has the client returned the short pre-review brief by the agreed date?", "The brief protects field time but should remain short and operational.", "Check whether it describes the work rather than a preferred solution.", "D09 · PROCESS NOT SOLUTION", "Send one focused reminder with the consequence for readiness.", "HOLD · PRE-REVIEW BRIEF", "Brief version, date received, missing answers and follow-up owner."),
      decision("D09", "Process lead", "Does the brief describe the live process and symptoms rather than prescribe technology or training?", "The review must diagnose the constraint before choosing an intervention.", "Use the description as a provisional hypothesis only.", "D10 · SOURCE ARTEFACTS", "Reframe the brief around the actual work and result.", "RETURN · D08", "Stated symptom, requested solution, reframed process and decision question."),
      decision("D10", "Client owner", "Have the artefacts currently used to run the process been supplied or made available?", "Real forms, spreadsheets, messages, reports and records reveal controls that presentations hide.", "Register the artefacts without analysing them as final truth.", "D11 · INFORMATION SAFETY", "Test whether live observation can compensate for the missing material.", "D13 · OBSERVABILITY", "Artefact, owner, version, current use and access location."),
      decision("D11", "Information owner", "Will the review expose personal, confidential, safety-critical or security-sensitive information?", "The diagnostic does not justify uncontrolled copying or circulation of client information.", "Define the safe viewing, note-taking and retention route.", "D12 · SECURE HANDLING", "Proceed with ordinary controlled working records.", "D13 · OBSERVABILITY", "Classification, affected records, restriction and responsible owner."),
      decision("D12", "Information owner + process lead", "Is there an approved handling method that still allows useful observation?", "Security must shape the method rather than be bypassed for convenience.", "Apply the controls to devices, notes, images and evidence.", "D13 · OBSERVABILITY", "Redesign the evidence route or move the review.", "HOLD · INFORMATION HANDLING", "Allowed access, prohibited capture, storage, retention, deletion and approver."),
      decision("D13", "Client owner", "Is live or recently completed work likely to be observable during the half-day?", "The review depends on following work, not discussing a hypothetical ideal process.", "Select a representative window and likely cases.", "D14 · READINESS CONFIRMATION", "Arrange a recent traceable case or reschedule for a real operating window.", "HOLD · OBSERVATION WINDOW", "Expected volume, timing, candidate cases, exceptions and fallback evidence."),
      decision("D14", "Process lead + client owner", "Are the agenda, maximum four primary participants and explicit exclusions confirmed?", "A crowded workshop dilutes observation and creates expectations outside the fixed product.", "Release the fieldwork plan.", "D15 · REQUIRED PEOPLE", "Correct the attendance or scope before arrival.", "HOLD · REVIEW READINESS", "Agenda, participants, roles, exclusions, arrival plan and evidence request."),
    ],
  },
  {
    number: "03",
    title: "Open the fieldwork correctly",
    purpose: "Align the room on the decision and boundary before following the work itself.",
    decisions: [
      decision("D15", "Process lead", "Are the accountable process owner and at least one actual performer present?", "The review needs both the intended result and the lived method in the room.", "Open the review with the decision question.", "D16 · DECISION RESTATEMENT", "Test whether an authorised owner and credible performer can join promptly.", "HOLD · REQUIRED PEOPLE", "Attendees, roles, authority, absences and recovery decision."),
      decision("D16", "Client owner", "Does the group agree on the decision the review must support?", "The half-day should not chase every frustration surrounding the process.", "Display and record the agreed decision question.", "D17 · START AND END", "Clarify or narrow it before observing work.", "HOLD · DECISION CLARITY", "Agreed wording, decision maker, deadline and excluded questions."),
      decision("D17", "Process lead + performer", "Can the group identify one observable start signal and one evidence-based endpoint?", "A process boundary should be recognisable in live work, not only in a diagram.", "Mark the start, endpoint and adjacent handoffs.", "D18 · DESCRIBED PATH", "Narrow the boundary until start and finish are observable.", "HOLD · PROCESS BOUNDARY", "Trigger, first owner, endpoint, completion evidence and exclusions."),
      decision("D18", "Process performer", "Do participants describe the normal path consistently enough to begin?", "Differences are useful evidence, but the group still needs a provisional path to follow.", "Treat the shared path as a hypothesis to test.", "D19 · CONTROLS", "Record the conflicting versions without forcing false agreement.", "D19 · CONTROLS", "Each described path, source, disagreement and hypothesis selected."),
      decision("D19", "Process owner", "Can the owner name the controls and evidence that should keep the process reliable?", "Controls reveal what the organisation believes must not fail.", "Identify where each control should appear during observation.", "D20 · OBSERVATION PERMISSION", "Record the missing or informal control as a finding to test.", "D20 · OBSERVATION PERMISSION", "Control, purpose, owner, frequency, evidence and consequence."),
      decision("D20", "Process owner + information owner", "Does 2KO have permission to follow the selected live or recent case through the boundary?", "Access must cover the evidence trail, people and systems the case actually touches.", "Begin the controlled observation trace.", "D21 · EVIDENCE VIABILITY", "Switch to an approved case or evidence route.", "D21 · EVIDENCE VIABILITY", "Case reference, consent or authority, restrictions and permitted evidence."),
      decision("D21", "Process lead", "Can the approved observation route still answer the decision within the remaining time?", "A constrained review should stop honestly rather than manufacture confidence.", "Start at the real trigger and follow the work.", "D22 · LIVE CASE", "Reschedule, narrow the question or recommend a fuller audit.", "END · INSUFFICIENT FIELD ACCESS", "Remaining time, evidence available, gap, decision and next option."),
    ],
  },
  {
    number: "04",
    title: "Follow the work, not the story",
    purpose: "Trace a real case from instruction to evidence and separate observation from explanation at every step.",
    decisions: [
      decision("D22", "Process lead", "Is a live case active or ready to enter the agreed boundary?", "A live case offers the strongest evidence of sequence, waiting and workarounds.", "Record the real trigger and follow the case.", "D23 · TRIGGER EVIDENCE", "Test whether a recently completed case can be reconstructed.", "D24 · RECENT CASE TRACE", "Case reference, trigger time, source, owner and selection reason."),
      decision("D23", "Process performer", "Is the instruction or trigger visible in the record used to start work?", "Unrecorded starts create ambiguity about priority, responsibility and elapsed time.", "Capture the source and first ownership decision.", "D25 · STEP OWNERSHIP", "Record the informal or missing trigger as observed evidence.", "D25 · STEP OWNERSHIP", "Trigger source, content, timestamp, receiver and missing fields."),
      decision("D24", "Process performer + record owner", "Can a recent representative case be reconstructed from trustworthy records?", "A remembered example alone cannot support a defensible recommendation.", "Trace the case and label any gaps as reported rather than observed.", "D25 · STEP OWNERSHIP", "Stop the trace and protect the integrity of the conclusion.", "END · NO RELIABLE CASE", "Records found, missing evidence, reported facts and decision to continue or stop."),
      decision("D25", "Process lead", "Can each material step be tied to a person, system or rule that owns the next action?", "Unclear ownership is often the mechanism behind waiting and repeated chasing.", "Build the observed sequence with owners and timestamps.", "D26 · FLOW LOSS", "Mark every ownership break and how work is recovered.", "D26 · FLOW LOSS", "Step, input, action, owner, system, wait and output."),
      decision("D26", "Process lead + performer", "Does the case contain a handoff, queue, re-entry, workaround or repeated approval?", "These are common signals that the process spends more time waiting or recovering than progressing.", "Test whether the loss is material and repeatable.", "D27 · MATERIALITY", "Continue to the exception and control path.", "D28 · EXCEPTIONS AND CONTROLS", "Loss type, location, duration, cause offered and evidence source."),
      decision("D27", "Process owner + performer", "Is the observed loss material to the result and likely to recur?", "One awkward case should not automatically become a redesign programme.", "Record a bounded estimate and corroborating evidence.", "D28 · EXCEPTIONS AND CONTROLS", "Label it as local variation rather than the principal constraint.", "D28 · EXCEPTIONS AND CONTROLS", "Frequency, duration or impact, corroboration, confidence and limitation."),
      decision("D28", "Process lead", "Can the team show how meaningful exceptions and required controls are handled?", "The normal path is incomplete without the cases where rules fail or judgement is required.", "Trace at least one exception or its evidence trail.", "D29 · COMPLETION EVIDENCE", "Record that exception ownership or control evidence is absent.", "D29 · COMPLETION EVIDENCE", "Exception, decision authority, action, evidence, escalation and outcome."),
      decision("D29", "Process owner", "Is the process endpoint supported by evidence that the intended result was achieved?", "Work being passed onward is not necessarily proof of completion or value.", "Close the trace and move into diagnosis.", "D30 · PRINCIPAL FAILURE", "Treat the missing or unreliable completion evidence as an observed finding.", "D30 · PRINCIPAL FAILURE", "Endpoint, completion evidence, result, downstream acceptance and gap."),
    ],
  },
  {
    number: "05",
    title: "Choose the smallest responsible move",
    purpose: "Use the observed mechanism—not the client’s opening preference—to select the primary recommendation.",
    decisions: [
      decision("D30", "Process lead", "Is one principal failure supported by the observed case and corroborating evidence?", "A concise review should name the dominant mechanism without pretending to prove every cause.", "State the failure and test whether it sits inside the agreed boundary.", "D31 · BOUNDARY CAUSE", "Separate what was observed from what is still only reported.", "D32 · EVIDENCE SUFFICIENCY", "Failure statement, observed mechanism, corroboration and confidence."),
      decision("D31", "Process lead + client owner", "Does the likely cause sit substantially inside the reviewed process boundary?", "A local process change cannot responsibly solve an enterprise-wide or upstream cause.", "Test the process, people and technology routes.", "D33 · PROCESS ENABLEMENT", "Decide whether the remaining evidence can settle the wider cause.", "D32 · EVIDENCE SUFFICIENCY", "Cause boundary, upstream or downstream dependency, owner and evidence."),
      decision("D32", "Process lead", "Can the missing evidence be gathered credibly within the remaining half-day?", "The timebox is a control; uncertainty must not be hidden by confident wording.", "Gather only the evidence needed and repeat the diagnosis test.", "RETURN · D30", "Recommend an audit, a different boundary or no current intervention.", "ROUTE · AUDIT / RESCOPE / STOP", "Missing evidence, time remaining, collection route and confidence limit."),
      decision("D33", "Process lead + performer", "Does the current process allow a competent person to produce the correct result reliably?", "If the workflow itself blocks correct work, training or software alone will not repair it.", "Test whether capability is the primary remaining constraint.", "D34 · CAPABILITY CAUSE", "Recommend process clarification or redesign first.", "ROUTE · PROCESS, THEN D39", "Blocking rule, missing ownership, sequence defect, control gap and proposed change."),
      decision("D34", "Capability lead", "Would the process work reliably if the responsible people had the required practised capability?", "Training is appropriate only when knowledge or skill is causal.", "Recommend a bounded capability intervention with workplace application.", "ROUTE · TRAINING, THEN D39", "Continue to test whether repeatable rules justify automation.", "D35 · AUTOMATION FIT", "Roles, capability gap, required behaviour, assessment and reinforcement."),
      decision("D35", "Automation lead", "Are the trigger, rules, authority, normal path and meaningful exceptions stable enough to automate?", "Automation should remove controlled repetition, not accelerate ambiguity.", "Recommend a bounded automation validation or pilot.", "ROUTE · AUTOMATION, THEN D39", "Test whether fragmented records require a system response.", "D36 · SYSTEM FIT", "Trigger, volume, rules, exceptions, authority and manual effort."),
      decision("D36", "Systems lead", "Is the principal failure caused by fragmented records, missing visibility or an inadequate operating system?", "A system is justified by the process control it enables, not by a general desire to digitise.", "Recommend the closest fixed product or a scoped system route.", "ROUTE · SYSTEM, THEN D39", "Test whether the question is larger than this review can support.", "D37 · EVIDENCE DEPTH", "Records, users, handoffs, visibility gap, control need and integrations."),
      decision("D37", "Diagnostic lead", "Does the decision require quantified evidence across several processes, sites or material investment?", "A half-day review should not make a large investment case from one bounded observation.", "Recommend the appropriate Process and Automation Audit.", "ROUTE · AUDIT, THEN D39", "Test whether an existing product solves the bounded need.", "D38 · EXISTING PRODUCT", "Decision value, evidence breadth, sites, processes, investment and exposure."),
      decision("D38", "Process + solution lead", "Does an existing off-the-shelf product cover the need without material process invention?", "The responsible answer may be to use an available tool rather than commission 2KO to build one.", "Recommend the product and the conditions for adoption.", "ROUTE · PRODUCT, THEN D39", "Carry the evidence into the intervention-necessity decision.", "D39 · INTERVENTION NECESSITY", "Product, fit, gaps, ownership, adoption condition and reason not to build."),
    ],
  },
  {
    number: "06",
    title: "Issue a defensible decision brief",
    purpose: "Convert the half-day into a concise factual memo, not a transcript or a proposal disguised as diagnosis.",
    decisions: [
      decision("D39", "Process lead", "Is any intervention currently justified by the evidence?", "The most useful recommendation may be to standardise an existing practice, wait, refer or do nothing.", "Name the single primary recommendation and its decision conditions.", "D40 · PRIMARY RECOMMENDATION", "Write a clear do-not-build, defer or refer recommendation.", "ROUTE · STOP / DEFER / REFER, THEN D40", "Recommendation, rationale, alternative rejected and reopening condition."),
      decision("D40", "Process lead", "Does the memo have one primary recommendation rather than a menu of equal options?", "The client paid for a decision, not an unranked list that returns the uncertainty to them.", "State the next step and why it is the smallest responsible move.", "D41 · EVIDENCE LABELS", "Rank the alternatives and select one recommendation.", "RETURN · D40", "Primary route, secondary option, rejected options and selection reason."),
      decision("D41", "Process lead", "Are observed, recorded, reported and inferred statements visibly distinguished?", "Evidence strength must remain clear after the people in the room forget the conversation.", "Keep the labels and confidence limits in the final memo.", "D42 · IMPACT DISCIPLINE", "Correct every blurred or unsupported statement.", "RETURN · D41", "Evidence item, type, source, date and confidence."),
      decision("D42", "Measurement lead", "Is the likely impact stated proportionately without invented precision?", "A bounded review can identify materiality, but it is not automatically a detailed financial model.", "State the bounded impact and what remains unquantified.", "D43 · SCOPE HONESTY", "Remove false precision or recommend an audit for quantification.", "RETURN · D42", "Impact basis, arithmetic if used, assumptions, exclusions and confidence."),
      decision("D43", "Process lead", "Does the memo clearly state what the review did and did not establish?", "Explicit exclusions protect the client from over-reading a concise diagnostic.", "Confirm the one process, site, participants and evidence limits.", "D44 · COMMERCIAL SEPARATION", "Add the missing boundary and limitation statements.", "RETURN · D43", "Boundary, evidence period, participants, exclusions and unresolved questions."),
      decision("D44", "Commercial + process lead", "Is the recommendation free from unapproved scope, architecture, prototype promises and disguised sales claims?", "The review may recommend a next engagement, but it must not imply work that has not been scoped or authorised.", "Separate the diagnostic conclusion from any optional commercial next step.", "D45 · PEER CHECK", "Remove or explicitly qualify the unsupported commitment.", "RETURN · D44", "Commercial references, assumptions, unpriced work and corrective edit."),
      decision("D45", "Independent reviewer", "Has somebody who did not lead the fieldwork checked the logic, evidence and language?", "A short peer review catches overclaiming, missing alternatives and unclear decisions.", "Release the factual draft to the client owner.", "D46 · FACTUAL CHECK", "Return it with specific evidence or reasoning corrections.", "RETURN · D45", "Reviewer, checklist result, challenges, changes and approval time."),
      decision("D46", "Client owner + process lead", "Have factual corrections been resolved without allowing the recommendation to be rewritten by preference?", "The client should correct facts; 2KO remains accountable for the independent diagnosis.", "Issue the controlled three-to-four-page decision brief and schedule the decision conversation.", "END · DECISION BRIEF ISSUED", "Resolve factual disputes, retain the evidence trail and delay issue if necessary.", "HOLD · FACTUAL RESOLUTION", "Final version, corrections, unresolved disagreement, issue date and next decision."),
    ],
  },
];

export default function ProcessReviewDecisionTree() {
  return (
    <DecisionTreeCanvas
      ariaLabel="2KO internal Half-Day Process Review decision canvas"
      toolbarTitle="HALF-DAY PROCESS REVIEW CANVAS"
      title="Half-Day Process Review"
      introduction="Follow one bounded process from booked review through live observation, disciplined diagnosis and a concise build-or-do-not-build decision brief."
      stages={stages}
      finalTitle="The recommendation follows the evidence—not the opening sales preference."
      finalCopy="Issue a short controlled memo that identifies the principal failure, the smallest responsible next move and the limits of what one half-day can prove."
    />
  );
}
