export function ProjectArchitecture() {
  const phases = [["Define", "3 topics", "100"], ["Measure", "4 topics", "100"], ["Analyse", "5 topics", "72"], ["Improve", "4 topics", "28"], ["Control", "3 topics", "0"], ["Executive summary", "1 topic", "0"]];
  return <figure className="sfy-project"><header><span>PROJECT · REDUCE DEFECT RATE</span><b>3 REVIEWERS · ON TRACK</b></header><div className="sfy-project-stage"><aside><span>PROJECT OWNER</span><strong>Naledi Mokoena</strong><small>Green Belt · Cohort 24</small><dl><div><dt>Baseline</dt><dd>4.8%</dd></div><div><dt>Target</dt><dd>&lt; 2.0%</dd></div><div><dt>Sponsor</dt><dd>T. Nkosi</dd></div><div><dt>Due</dt><dd>28 Nov</dd></div></dl></aside><main>{phases.map(([name, topics, progress], index) => <article key={name} data-current={index === 2}><i>{String(index + 1).padStart(2,"0")}</i><div><strong>{name}</strong><small>{topics}</small></div><span><b style={{width:`${progress}%`}} /></span><em>{progress}%</em></article>)}</main><aside className="sfy-project-feed"><span>RECENT EVIDENCE</span><div><i>✓</i><p>Measurement plan approved<small>Trainer · 08:42</small></p></div><div><i>↑</i><p>Process map submitted<small>Delegate · yesterday</small></p></div><div><i>AI</i><p>Rubric evaluation logged<small>3 of 4 criteria met</small></p></div><div><i>↻</i><p>CTQ revision requested<small>Due Friday</small></p></div></aside></div><figcaption>Illustrative DMAIC project record · example values</figcaption></figure>;
}

export function AIEvaluation() {
  return <figure className="sfy-ai"><header><span>AI EVALUATION · SOLUTION 3.2</span><b>TRAINER REVIEW REQUIRED</b></header><div className="sfy-ai-stage"><main><div className="sfy-ai-title"><span>CAUSE & EFFECT ANALYSIS</span><h3>Submission evaluated against the project rubric.</h3><p>AI structures the first response. A named practitioner can review, override and sign off every result.</p></div><div className="sfy-ai-checks">{[["Identifies the primary process input","MET"],["Cites the approved measurement plan","MET"],["Quantifies the likely variation source","PARTIAL"],["Connects the cause to a control method","REVISE"]].map(([item,state],index)=><div key={item}><i>{String(index+1).padStart(2,"0")}</i><span>{item}</span><strong data-state={state}>{state}</strong></div>)}</div></main><aside><span>PRACTITIONER NOTE</span><p>Strong link between the input and the measurement plan. Tighten the evidence for the variation source before the Improve-phase recommendation is accepted.</p><div><i>SD</i><span><strong>Sizwe Dlamini</strong><small>Master Black Belt · reviewed 09:16</small></span></div><footer><button type="button">Return for revision</button><button type="button">Approve</button></footer></aside></div><figcaption><span>Illustrative evaluation record</span><span>AI ASSISTS · HUMAN AUTHORITY REMAINS ON RECORD</span></figcaption></figure>;
}

export function BenefitsRegister() {
  const benefits = [["SIG–024","Reduce packaging defects","Verified","R1.42m"],["SIG–031","Release invoice capacity","Measured","R684k"],["SIG–035","Shorten approval lead time","Sustaining","R392k"],["SIG–041","Reduce stock variance","Forecast","R276k"]];
  return <figure className="sfy-benefits"><header><div><span>PORTFOLIO · BENEFITS REGISTER</span><h3>Value survives the slide deck.</h3></div><div><small>VERIFIED + MEASURED</small><strong>R2.50m</strong></div></header><div className="sfy-benefit-summary"><article><span>12</span><small>active projects</small></article><article><span>7</span><small>sponsor-approved</small></article><article><span>91d</span><small>longest sustain period</small></article><article><span>82%</span><small>evidence complete</small></article></div><div className="sfy-benefit-table"><div><span>REFERENCE</span><span>IMPROVEMENT</span><span>EVIDENCE STATE</span><span>ANNUALISED</span></div>{benefits.map(([ref,name,state,value])=><article key={ref}><span>{ref}</span><strong>{name}</strong><span data-state={state}>{state}</span><b>{value}</b></article>)}</div><figcaption>Illustrative benefits register · example records and values · not a client result</figcaption></figure>;
}
