/**
 * Generates exact Africa geometry for the hero map.
 *
 * Source is Natural Earth (via the world-atlas package) at 1:50m, projected
 * with d3-geo and written out as plain SVG path strings. Nothing is drawn by
 * hand and nothing is approximated — the coastline is the real coastline, and
 * the city markers are real coordinates run through the same projection, so
 * they land exactly where they belong.
 *
 * Run: node scripts/build-africa.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { feature } from "topojson-client";
import { geoMercator, geoPath, geoGraticule } from "d3-geo";

const WIDTH = 1000;
const HEIGHT = 1040;

/** ISO 3166-1 numeric codes for the African continent. */
const AFRICA = new Set([
  "012","024","072","108","120","132","140","148","174","178","180","204","226",
  "231","232","262","266","270","288","324","384","404","426","430","434","450",
  "454","466","478","480","504","508","516","562","566","624","646","678","686",
  "690","694","706","710","716","728","729","732","748","768","788","800","818",
  "834","854","894",
]);

const topo = JSON.parse(
  readFileSync(`node_modules/world-atlas/countries-${process.env.RES ?? "50m"}.json`, "utf8"),
);
const countries = feature(topo, topo.objects.countries).features;
const african = countries.filter((f) => AFRICA.has(String(f.id).padStart(3, "0")));

if (african.length < 40) {
  throw new Error(`Only matched ${african.length} African countries — check the ISO list.`);
}

const collection = { type: "FeatureCollection", features: african };

const projection = geoMercator().fitExtent(
  [
    [28, 28],
    [WIDTH - 28, HEIGHT - 28],
  ],
  collection,
);
// One decimal place is well below a screen pixel at this scale and cuts the
// generated file by roughly two thirds. The shape is unchanged.
const path = geoPath(projection).digits(1);

/** Major centres. Coordinates are [longitude, latitude]. */
const CITIES = [
  { name: "Johannesburg", coords: [28.0473, -26.2041], home: true },
  { name: "Cape Town", coords: [18.4241, -33.9249] },
  { name: "Durban", coords: [31.0218, -29.8587] },
  { name: "Gqeberha", coords: [25.6022, -33.9608] },
  { name: "Gaborone", coords: [25.9231, -24.6282] },
  { name: "Windhoek", coords: [17.0658, -22.5609] },
  { name: "Maputo", coords: [32.5732, -25.9692] },
  { name: "Harare", coords: [31.0335, -17.8252] },
  { name: "Lusaka", coords: [28.3228, -15.3875] },
  { name: "Luanda", coords: [13.2894, -8.839] },
  { name: "Kinshasa", coords: [15.2663, -4.4419] },
  { name: "Dar es Salaam", coords: [39.2083, -6.7924] },
  { name: "Nairobi", coords: [36.8219, -1.2921] },
  { name: "Kampala", coords: [32.5825, 0.3476] },
  { name: "Addis Ababa", coords: [38.7469, 9.032] },
  { name: "Lagos", coords: [3.3792, 6.5244] },
  { name: "Accra", coords: [-0.187, 5.6037] },
  { name: "Abidjan", coords: [-4.0083, 5.36] },
  { name: "Dakar", coords: [-17.4677, 14.7167] },
  { name: "Cairo", coords: [31.2357, 30.0444] },
  { name: "Casablanca", coords: [-7.5898, 33.5731] },
];

const cities = CITIES.map((city) => {
  const [x, y] = projection(city.coords);
  return {
    name: city.name,
    home: Boolean(city.home),
    x: Number(x.toFixed(2)),
    y: Number(y.toFixed(2)),
  };
});

/**
 * An ordered tour rather than a radial burst: the line travels from one centre
 * to the next, and each arrival becomes the departure for the following hop.
 * Route is nearest-neighbour from Johannesburg, which produces a natural sweep
 * up the continent instead of an arbitrary order.
 */
const home = cities.find((c) => c.home);
const remaining = cities.filter((c) => !c.home);
const route = [home];

while (remaining.length) {
  const last = route[route.length - 1];
  let bestIndex = 0;
  let bestDistance = Infinity;
  remaining.forEach((candidate, i) => {
    const distance = Math.hypot(candidate.x - last.x, candidate.y - last.y);
    if (distance < bestDistance) {
      bestDistance = distance;
      bestIndex = i;
    }
  });
  route.push(remaining.splice(bestIndex, 1)[0]);
}

const arcs = route.slice(0, -1).map((from, i) => {
  const to = route[i + 1];
  const mx = (from.x + to.x) / 2;
  const my = (from.y + to.y) / 2;
  const dx = to.x - from.x;
  const dy = to.y - from.y;
  const distance = Math.hypot(dx, dy) || 1;
  // Perpendicular offset, scaled by span, gives the lifted flight-path bow.
  const lift = distance * 0.24;
  const nx = -dy / distance;
  const ny = dx / distance;
  return {
    from: from.name,
    to: to.name,
    x1: from.x,
    y1: from.y,
    x2: to.x,
    y2: to.y,
    d: `M ${from.x} ${from.y} Q ${(mx + nx * lift).toFixed(2)} ${(my + ny * lift).toFixed(2)} ${to.x} ${to.y}`,
  };
});

const graticule = geoGraticule().stepMinor([10, 10]);

const out = `// GENERATED by scripts/build-africa.mjs — do not edit by hand.
// Source: Natural Earth 1:50m via world-atlas, projected with d3-geo (Mercator).

export const MAP = { width: ${WIDTH}, height: ${HEIGHT} } as const;

/** Every African country as its own path, for the interior borders. */
export const COUNTRIES: string[] = ${JSON.stringify(african.map((f) => path(f)))};

/** The continent as a single outline. */
export const OUTLINE: string = ${JSON.stringify(path(collection))};

/** Ten-degree graticule, clipped to the map box. */
export const GRATICULE: string = ${JSON.stringify(path(graticule()))};

export type City = { name: string; home: boolean; x: number; y: number };
export const CITIES: City[] = ${JSON.stringify(cities)};

export type Arc = {
  from: string;
  to: string;
  x1: number; y1: number;
  x2: number; y2: number;
  d: string;
};

/** Ordered hops. Each arc departs from where the previous one landed. */
export const TOUR: Arc[] = ${JSON.stringify(arcs)};
`;

writeFileSync("src/lib/africa-map.ts", out);
console.log(`countries: ${african.length}, cities: ${cities.length}, arcs: ${arcs.length}`);
