/**
 * Legacy redirect coverage report.
 *
 *   npm run redirects:report
 *
 * Runs every path in docs/redirects/legacy-inventory.txt through the resolver
 * and writes docs/redirects/legacy-map.md — the table to review before this
 * ships, and the record of what was decided afterwards.
 *
 * Deliberate 404s are listed as prominently as the redirects. A URL left to
 * miss is a decision, and an undocumented one looks identical to an oversight.
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { legacyDestination } from "../src/lib/legacy-redirects.ts";

/**
 * Every route the site actually serves, read off the filesystem rather than
 * kept as a list here, so a new page cannot quietly start matching a legacy
 * rule. The patterns are loose by design — `/{something}-2` and `/product/…`
 * cover URLs that were never archived — and loose patterns are exactly the kind
 * that swallow a live route six months from now.
 */
function liveRoutes(dir: string, prefix = ""): string[] {
  const found: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.name === "page.tsx") found.push(prefix || "/");
    if (!entry.isDirectory()) continue;
    // Route groups like (site) do not appear in the URL.
    const segment = /^\(.+\)$/.test(entry.name) ? "" : `/${entry.name}`;
    found.push(...liveRoutes(`${dir}/${entry.name}`, prefix + segment));
  }
  return found;
}

/**
 * Slugs are scraped rather than imported: those modules import `@/lib/pricing`
 * through the tsconfig path alias, which Node's TypeScript stripping does not
 * resolve. A regex over the source keeps this script dependency-free.
 */
function slugs(file: string, prefix: string) {
  return [...readFileSync(file, "utf8").matchAll(/\bslug:\s*"([^"]+)"/g)].map(
    (m) => `${prefix}/${m[1]}`,
  );
}

const routes = [
  ...liveRoutes("src/app").filter((r) => !r.includes("[")),
  ...slugs("src/lib/websites.ts", "/websites"),
  ...slugs("src/lib/products.ts", "/systems"),
];
const captured = routes.filter((r) => legacyDestination(r));
if (captured.length) {
  console.error(
    `\n  \u2716 These live routes are captured by a legacy rule and would ` +
      `redirect away:\n${captured.map((r) => `      ${r}`).join("\n")}\n`,
  );
  process.exit(1);
}

const INVENTORY = "docs/redirects/legacy-inventory.txt";
const OUT = "docs/redirects/legacy-map.md";

const paths = readFileSync(INVENTORY, "utf8")
  .split("\n")
  .map((line) => line.trim())
  .filter((line) => line && !line.startsWith("#"))
  // Assets rather than pages: nothing to redirect a PDF or a map overlay to.
  .filter((line) => !/\.(pdf|jfif|kml|jpg|png|gif)$/i.test(line));

const resolved: [string, string][] = [];
const missed: string[] = [];
for (const path of paths) {
  const to = legacyDestination(path);
  if (to) resolved.push([path, to]);
  else missed.push(path);
}

const offsite = resolved.filter(([, to]) => to.startsWith("http"));
const onsite = resolved.filter(([, to]) => !to.startsWith("http"));

const byTarget = new Map<string, string[]>();
for (const [from, to] of resolved) {
  byTarget.set(to, [...(byTarget.get(to) ?? []), from]);
}

const pct = (n: number) => `${((n / paths.length) * 100).toFixed(1)}%`;

const md = `# Legacy URL redirect map

Generated by \`npm run redirects:report\` from \`legacy-inventory.txt\`.
Do not edit by hand — change \`src/lib/legacy-redirects.ts\` and regenerate.

| | Count | Share |
|---|---:|---:|
| Legacy paths in the inventory | ${paths.length} | |
| Redirected | **${resolved.length}** | ${pct(resolved.length)} |
| → to sixsigmasouthafrica.co.za | ${offsite.length} | ${pct(offsite.length)} |
| → to a page on 2ko.co.za | ${onsite.length} | ${pct(onsite.length)} |
| Left to 404 on purpose | ${missed.length} | ${pct(missed.length)} |

The inventory is what the Wayback Machine and the archived WordPress sitemaps
still hold. It is a sample of what Google indexed, not the whole of it, so the
city-page and product rules are patterns rather than a fixed list: a legacy URL
that never got archived still resolves if it followed the same shape.

## Destinations, by how much traffic each inherits

| Destination | Legacy URLs |
|---|---:|
${[...byTarget.entries()]
  .sort((a, b) => b[1].length - a[1].length)
  .map(([to, from]) => `| \`${to}\` | ${from.length} |`)
  .join("\n")}

## Left to 404 on purpose

These are retired lines with no honest equivalent. A redirect to a page that
does not answer the query reads as a soft 404 to Google and as a bait-and-switch
to the visitor, so they get the 404 page and its onward links instead.

${missed.length ? missed.map((p) => `- \`${p}\``).join("\n") : "_None._"}

## Every redirect

| Legacy URL | Destination |
|---|---|
${resolved
  .sort((a, b) => a[0].localeCompare(b[0]))
  .map(([from, to]) => `| \`${from}\` | ${to.startsWith("http") ? `**${to.replace("https://sixsigmasouthafrica.co.za", "SSSA")}**` : `\`${to}\``} |`)
  .join("\n")}
`;

writeFileSync(OUT, md);
console.log(`  ${resolved.length}/${paths.length} redirected (${pct(resolved.length)})`);
console.log(`  ${offsite.length} to the Six Sigma site, ${onsite.length} on 2ko.co.za`);
console.log(`  ${missed.length} left to 404 on purpose`);
console.log(`\n  Written to ${OUT}\n`);
